version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:14.17.3
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn build
      # - run: yarn test 